spring:
  datasource:
    url: jdbc:postgresql:pharmagator
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: validate


pharmagator:
  data-providers:
    apteka-ds:
      url: https://api-int.apteka-ds.com.ua/api/v1
      category-fetch-url: /category-menu
      category-path: /cat-prods-by-page
    aptslav:
      url: https://aptslav.com.ua:3000/api/v1/categories
      category-fetch-url-arguments: ?fields=id,name,icon,externalId,children.id,children.name,children.icon&embed=children&take=10&sort=externalId&parentId[equal]=null&active[equal]=true
      category-path: /products?take=15&skip=0&sort=externalId&inStock=true&fields=name,externalId,viewed,id,images.id,images.filename,images.uri&embed=images
