spring:
  datasource:
    url: jdbc:postgresql:pharmagator
    username: postgres
    password: xhbynwa
  jpa:
    hibernate:
      ddl-auto: validate
pharmagator:
  data-providers:
    aptslav:
      base-url: https://aptslav.com.ua:3000/api/v1
      categories-url: /categories
      medicines-uri: /categories/87/products